
import { Lesson } from './types';

export const APP_NAME = "Weekly Scripture Study";

export const BOOK_IDS: Record<string, number> = {
  "Ezra": 15,
  "Nehemiah": 16,
  "Esther": 17,
  "Ezekiel": 26,
  "Daniel": 27,
  "Haggai": 37,
  "Zechariah": 38,
  "Malachi": 39,
  "Romans": 45
};

export const BOOK_NAMES_ZH: Record<string, string> = {
  "Ezekiel": "以西结书",
  "Daniel": "但以理书",
  "Ezra": "以斯拉记",
  "Esther": "以斯帖记",
  "Haggai": "哈该书",
  "Zechariah": "撒迦利亚书",
  "Nehemiah": "尼希米记",
  "Malachi": "玛拉基书",
  "Romans": "罗马书"
};

export const BOOK_NAMES_ZH_HANT: Record<string, string> = {
  "Ezekiel": "以西結書",
  "Daniel": "但以理書",
  "Ezra": "以斯拉記",
  "Esther": "以斯帖記",
  "Haggai": "哈該書",
  "Zechariah": "撒迦利亞書",
  "Nehemiah": "尼希米記",
  "Malachi": "瑪拉基書",
  "Romans": "羅馬書"
};

export const CURRICULUM: Lesson[] = [
  { 
    id: 1, 
    weekStart: "2025-09-29",
    titleEn: "Ezekiel: God's Prophet in Exile", 
    titleZh: "以西结：被掳的上帝先知", 
    passage: { book: "Ezekiel", chapterStart: 1, chapterEnd: 2 },
    doctrineEn: "God the Father",
    doctrineZh: "圣父",
    highlightedPassage: { book: "Ezekiel", chapterStart: 1, verseStart: 28, chapterEnd: 1, verseEnd: 28 },
    highlightedVerseZh: "“下雨的日子云中虹的形状怎样，周围光辉的形状也是怎样。这就是耶和华荣耀的形象。我一看见就俯伏在地，又听见一位说话的声音。”"
  },
  { 
    id: 2, 
    weekStart: "2025-10-06",
    titleEn: "Hope for the Hopeless", 
    titleZh: "绝望者的盼望", 
    passage: { book: "Ezekiel", chapterStart: 36, verseStart: 16, chapterEnd: 37, verseEnd: 28 },
    doctrineEn: "Regeneration",
    doctrineZh: "重生",
    highlightedPassage: { book: "Ezekiel", chapterStart: 36, verseStart: 36, chapterEnd: 36, verseEnd: 36 },
    highlightedVerseZh: "“那时，在你们四围其余的外邦人必知道我耶和华修造那毁坏之处，培植那荒废之地。我耶和华说过，也必成就。”"
  },
  { 
    id: 3, 
    weekStart: "2025-10-13",
    titleEn: "Truth and Power During Exile", 
    titleZh: "被掳期间的真理与力量", 
    passage: { book: "Daniel", chapterStart: 1, chapterEnd: 2 },
    doctrineEn: "Fulfillment of Prophecy",
    doctrineZh: "预言的应验",
    highlightedPassage: { book: "Daniel", chapterStart: 2, verseStart: 19, chapterEnd: 2, verseEnd: 20 },
    highlightedVerseZh: "“但以理便称颂天上的上帝。但以理说：‘上帝的名是应当称颂的，从亘古直到永远！因为智慧能力都属乎祂。’”"
  },
  { 
    id: 4, 
    weekStart: "2025-10-20",
    titleEn: "Steadfast Faith and Humility", 
    titleZh: "坚守所信，坚持谦卑", 
    passage: { book: "Daniel", chapterStart: 3, chapterEnd: 4 },
    doctrineEn: "Judgment of Believers and Unbelievers",
    doctrineZh: "信徒与非信徒的审判",
    highlightedPassage: { book: "Daniel", chapterStart: 4, verseStart: 3, chapterEnd: 4, verseEnd: 3 },
    highlightedVerseZh: "“祂的神迹何其大，祂的奇事何其盛！祂的国是永远的，祂的权柄存到万代！”"
  },
  { 
    id: 5, 
    weekStart: "2025-10-27",
    titleEn: "Faith in Darkness and Lion's Den", 
    titleZh: "黑暗中及狮子坑里的信心", 
    passage: { book: "Daniel", chapterStart: 5, chapterEnd: 6 },
    doctrineEn: "Faith",
    doctrineZh: "信",
    highlightedPassage: { book: "Daniel", chapterStart: 6, verseStart: 27, chapterEnd: 6, verseEnd: 27 },
    highlightedVerseZh: "“祂护庇人，搭救人，在天上地下施行神迹奇事，救了但以理脱离狮子的口。”"
  },
  { 
    id: 6, 
    weekStart: "2025-11-03",
    titleEn: "Visions of World Oppression", 
    titleZh: "表达世界压迫的兽类异象", 
    passage: { book: "Daniel", chapterStart: 7, chapterEnd: 8 },
    doctrineEn: "Humanity: Fall and Judgment",
    doctrineZh: "人类：堕落与审判",
    highlightedPassage: { book: "Daniel", chapterStart: 7, verseStart: 27, chapterEnd: 7, verseEnd: 27 },
    highlightedVerseZh: "“国度、权柄和天下诸国的大权必赐给至高者的众圣民。祂的国是永远的，一切掌权的都必侍奉祂，顺从祂。”"
  },
  { 
    id: 7, 
    weekStart: "2025-11-10",
    titleEn: "Daniel's Prayer", 
    titleZh: "但以理的祷告", 
    passage: { book: "Daniel", chapterStart: 9, chapterEnd: 9 },
    doctrineEn: "Prayer",
    doctrineZh: "祷告",
    highlightedPassage: { book: "Daniel", chapterStart: 9, verseStart: 19, chapterEnd: 9, verseEnd: 19 },
    highlightedVerseZh: "“求主垂听，求主赦免，求主应允而行，为你自己不要迟延，我的上帝啊，因这城和这民都是称为你名下的。”"
  },
  { 
    id: 8, 
    weekStart: "2025-11-17",
    titleEn: "The Battle Belongs to the Lord", 
    titleZh: "争战属于耶和华", 
    passage: { book: "Daniel", chapterStart: 10, chapterEnd: 12 },
    doctrineEn: "Kingdom of God",
    doctrineZh: "上帝的国度",
    highlightedPassage: { book: "Daniel", chapterStart: 12, verseStart: 10, chapterEnd: 12, verseEnd: 10 },
    highlightedVerseZh: "“必有许多人使自己清净洁白，且被熬炼，但恶人仍必行恶。一切恶人都不明白，唯独智慧人能明白。”"
  },
  { 
    id: 9, 
    weekStart: "2025-11-24",
    titleEn: "End of Exile, Return of People", 
    titleZh: "被掳结束，上帝子民归回故国", 
    passage: { book: "Ezra", chapterStart: 1, chapterEnd: 2 },
    doctrineEn: "Fulfillment of Prophecy",
    doctrineZh: "预言的应验",
    highlightedPassage: { book: "Ezra", chapterStart: 1, verseStart: 1, chapterEnd: 1, verseEnd: 1 },
    highlightedVerseZh: "“波斯王居鲁士元年，耶和华为要应验借耶利米口所说的话，就激动波斯王居鲁士的心，使他下诏通告全国。”"
  },
  { 
    id: 10, 
    weekStart: "2025-12-01",
    titleEn: "Return and Rebuild", 
    titleZh: "归回故国，重建家园", 
    passage: { book: "Ezra", chapterStart: 3, chapterEnd: 6 },
    doctrineEn: "Substitution",
    doctrineZh: "替代",
    highlightedPassage: { book: "Ezra", chapterStart: 6, verseStart: 22, chapterEnd: 6, verseEnd: 22 },
    highlightedVerseZh: "“欢欢喜喜地守除酵节七日，因为耶和华使他们欢喜，又使亚述王的心转向他们，坚固他们的手，作以色列上帝殿的工程。”"
  },
  { 
    id: 11, 
    weekStart: "2025-12-08",
    titleEn: "New Beginning in the Promised Land", 
    titleZh: "在应许之地的新开始", 
    passage: { book: "Ezra", chapterStart: 7, chapterEnd: 8 },
    doctrineEn: "The Bible",
    doctrineZh: "圣经",
    highlightedPassage: { book: "Ezra", chapterStart: 7, verseStart: 10, chapterEnd: 7, verseEnd: 10 },
    highlightedVerseZh: "“以斯拉定志考究遵行耶和华的律法，又将律例、典章教训以色列人。”"
  },
  { 
    id: 12, 
    weekStart: "2025-12-15",
    titleEn: "Costly Compromise and Painful Obedience", 
    titleZh: "代价高昂的妥协和痛苦的服从", 
    passage: { book: "Ezra", chapterStart: 9, chapterEnd: 10 },
    doctrineEn: "Sin, Its Nature and Universality",
    doctrineZh: "罪、其特性及普遍性",
    highlightedPassage: { book: "Ezra", chapterStart: 9, verseStart: 10, chapterEnd: 9, verseEnd: 11 },
    highlightedVerseZh: "“我们的上帝啊，既是如此，我们还有什么话可说呢？因为我们已经离弃你的命令，就是你借你仆人众先知所吩咐的。”"
  },
  { 
    id: 13, 
    weekStart: "2025-12-22",
    titleEn: "The New Queen", 
    titleZh: "新王后", 
    passage: { book: "Esther", chapterStart: 1, chapterEnd: 2 },
    doctrineEn: "God's Sovereignty",
    doctrineZh: "上帝的至高主权",
    highlightedPassage: { book: "Esther", chapterStart: 2, verseStart: 17, chapterEnd: 2, verseEnd: 17 },
    highlightedVerseZh: "“王爱以斯帖过于爱众女，她在王眼前蒙宠爱比众处女更甚。王就把王后的冠冕戴在她头上，立她为王后，代替瓦实提。”"
  },
  { 
    id: 14, 
    weekStart: "2025-12-29",
    titleEn: "Outsmarting the Enemy", 
    titleZh: "智胜强敌", 
    passage: { book: "Esther", chapterStart: 3, chapterEnd: 7 },
    doctrineEn: "Satan and Demons",
    doctrineZh: "撒但和鬼魔",
    highlightedPassage: { book: "Esther", chapterStart: 4, verseStart: 14, chapterEnd: 4, verseEnd: 14 },
    highlightedVerseZh: "“此时你若闭口不言，犹大人必从别处得解脱、蒙拯救；你和你父家必至灭亡。焉知你得了王后的位分，不是为现今的机会吗？”"
  },
  { 
    id: 15, 
    weekStart: "2026-01-05",
    titleEn: "Justice Served", 
    titleZh: "正义得到伸张", 
    passage: { book: "Esther", chapterStart: 8, chapterEnd: 10 },
    doctrineEn: "Grace",
    doctrineZh: "恩典",
    highlightedPassage: { book: "Esther", chapterStart: 10, verseStart: 3, chapterEnd: 10, verseEnd: 3 },
    highlightedVerseZh: "“犹大人末底改做亚哈随鲁王的宰相，在犹大人中为大，得他众弟兄的喜悦，为本族的人求好处，向他们说和平的话。”"
  },
  { 
    id: 16, 
    weekStart: "2026-01-12",
    titleEn: "Turning Defeat into Focus", 
    titleZh: "将挫败转化为专注", 
    passage: { book: "Haggai", chapterStart: 1, chapterEnd: 2 },
    doctrineEn: "Sanctification",
    doctrineZh: "成圣",
    highlightedPassage: { book: "Haggai", chapterStart: 2, verseStart: 6, chapterEnd: 2, verseEnd: 7 },
    highlightedVerseZh: "“万军之耶和华如此说：‘过不多时，我必再一次震动天地、沧海与旱地。我必震动万国，万国的珍宝必都运来，我就使这殿满了荣耀。这是万军之耶和华说的。’”"
  },
  { 
    id: 17, 
    weekStart: "2026-01-19",
    titleEn: "Zechariah: Call to Return", 
    titleZh: "撒迦利亚书：呼召归向主", 
    passage: { book: "Zechariah", chapterStart: 1, verseStart: 1, chapterEnd: 1, verseEnd: 6 },
    doctrineEn: "Repentance",
    doctrineZh: "悔改",
    highlightedPassage: { book: "Zechariah", chapterStart: 1, verseStart: 3, chapterEnd: 1, verseEnd: 3 },
    highlightedVerseZh: "“所以你要对以色列人说：‘万军之耶和华如此说：你们要转向我，我就转向你们。这是万军之耶和华说的。’”"
  },
  { 
    id: 18, 
    weekStart: "2026-01-26",
    titleEn: "Zechariah's Night Visions (I)", 
    titleZh: "撒迦利亚的夜间异象（一）", 
    passage: { book: "Zechariah", chapterStart: 1, verseStart: 7, chapterEnd: 4, verseEnd: 14 },
    doctrineEn: "Holy Spirit",
    doctrineZh: "圣灵",
    highlightedPassage: { book: "Zechariah", chapterStart: 4, verseStart: 6, chapterEnd: 4, verseEnd: 7 },
    highlightedVerseZh: "“他对我说：‘这是耶和华指示所罗巴伯的。万军之耶和华说：不是倚靠势力，不是倚靠才能，乃是倚靠我的灵方能成事。大山哪，你算什么呢？在所罗巴伯面前，你必成为平地。’”"
  },
  { 
    id: 19, 
    weekStart: "2026-02-02",
    titleEn: "Zechariah's Night Visions (II)", 
    titleZh: "撒迦利亚的夜間異象（二）", 
    passage: { book: "Zechariah", chapterStart: 5, chapterEnd: 6 },
    doctrineEn: "Justification",
    doctrineZh: "称义",
    highlightedPassage: { book: "Zechariah", chapterStart: 6, verseStart: 12, chapterEnd: 6, verseEnd: 12 },
    highlightedVerseZh: "“对他说：‘万军之耶和华如此说：看哪，那名称为大卫苗裔的，他要在本处长起来，并要建造耶和华的殿。’”"
  },
  { 
    id: 20, 
    weekStart: "2026-02-09",
    titleEn: "Fasting and Feasting", 
    titleZh: "禁食与盛宴", 
    passage: { book: "Zechariah", chapterStart: 7, chapterEnd: 8 },
    doctrineEn: "Millennium",
    doctrineZh: "千禧年",
    highlightedPassage: { book: "Zechariah", chapterStart: 8, verseStart: 19, chapterEnd: 8, verseEnd: 19 },
    highlightedVerseZh: "“万军之耶和华如此说：四月、五月禁食的日子，七月、十月禁食的日子，必变为犹大家欢喜快乐的日子和欢乐的节期，所以你们要喜爱诚实与和平。”"
  },
  { 
    id: 21, 
    weekStart: "2026-02-16",
    titleEn: "Promise of the Coming King", 
    titleZh: "君王将临的应许", 
    passage: { book: "Zechariah", chapterStart: 9, chapterEnd: 11 },
    doctrineEn: "Holy Son",
    doctrineZh: "圣子",
    highlightedPassage: { book: "Zechariah", chapterStart: 9, verseStart: 16, chapterEnd: 9, verseEnd: 16 },
    highlightedVerseZh: "“当那日，耶和华他们的上帝必看祂的民如群羊，拯救他们。因为他们必像冠冕上的宝石，高举在祂的地以上。”"
  },
  { 
    id: 22, 
    weekStart: "2026-02-23",
    titleEn: "Promise of the Coming Victory", 
    titleZh: "胜利将临的应许", 
    passage: { book: "Zechariah", chapterStart: 12, chapterEnd: 14 },
    doctrineEn: "Kingdom of God",
    doctrineZh: "上帝的国度",
    highlightedPassage: { book: "Zechariah", chapterStart: 14, verseStart: 9, chapterEnd: 14, verseEnd: 9 },
    highlightedVerseZh: "“耶和华必做全地的王，那日耶和华必为独一无二的，祂的名也是独一无二的。”"
  },
  { 
    id: 23, 
    weekStart: "2026-03-02",
    titleEn: "Call to Rebuild the Wall", 
    titleZh: "重建城墙的呼召", 
    passage: { book: "Nehemiah", chapterStart: 1, chapterEnd: 3 },
    doctrineEn: "Believer's Cross",
    doctrineZh: "信徒的十字架",
    highlightedPassage: { book: "Nehemiah", chapterStart: 2, verseStart: 17, chapterEnd: 2, verseEnd: 17 },
    highlightedVerseZh: "“以后，我对他们说：‘我们所遭的难，耶路撒冷怎样荒凉，城门被火焚烧，你们都看见了。来吧，我们重建耶路撒冷的城墙，免得再受凌辱。’”"
  },
  { 
    id: 24, 
    weekStart: "2026-03-09",
    titleEn: "Facing Opposition", 
    titleZh: "面临反对", 
    passage: { book: "Nehemiah", chapterStart: 4, verseStart: 1, chapterEnd: 6, verseEnd: 14 },
    doctrineEn: "Suffering",
    doctrineZh: "苦难",
    highlightedPassage: { book: "Nehemiah", chapterStart: 4, verseStart: 6, chapterEnd: 4, verseEnd: 6 },
    highlightedVerseZh: "“这样，我们修造城墙，城墙就都连络，高至一半，因为百姓专心做工。”"
  },
  { 
    id: 25, 
    weekStart: "2026-03-16",
    titleEn: "Reading and Responding to the Law", 
    titleZh: "宣读并回应律法书", 
    passage: { book: "Nehemiah", chapterStart: 6, verseStart: 15, chapterEnd: 8, verseEnd: 18 },
    doctrineEn: "Humanity's Creation and Purpose",
    doctrineZh: "人类的受造与目的",
    highlightedPassage: { book: "Nehemiah", chapterStart: 8, verseStart: 18, chapterEnd: 8, verseEnd: 18 },
    highlightedVerseZh: "“从头一天直到末一天，以斯拉每日念上帝的律法书。众人守节七日，第八日照例有严肃会。”"
  },
  { 
    id: 26, 
    weekStart: "2026-03-23",
    titleEn: "Confession and Obedience", 
    titleZh: "认罪与顺服", 
    passage: { book: "Nehemiah", chapterStart: 9, chapterEnd: 10 },
    doctrineEn: "Repentance",
    doctrineZh: "悔改",
    highlightedPassage: { book: "Nehemiah", chapterStart: 9, verseStart: 3, chapterEnd: 9, verseEnd: 3 },
    highlightedVerseZh: "“那日的四分之一，站在自己的地方，念耶和华他们上帝的律法书；又四分之一，认罪，敬拜耶和华他们的上帝。”"
  },
  { 
    id: 27, 
    weekStart: "2026-03-30",
    titleEn: "Dedication and Renewal", 
    titleZh: "献礼与更新", 
    passage: { book: "Nehemiah", chapterStart: 11, chapterEnd: 13 },
    doctrineEn: "Deeds",
    doctrineZh: "行为",
    highlightedPassage: { book: "Nehemiah", chapterStart: 13, verseStart: 14, chapterEnd: 13, verseEnd: 14 },
    highlightedVerseZh: "“我的上帝啊，求你因这事记念我，不要涂抹我为上帝的殿与其中的礼节所行的善。”"
  },
  { 
    id: 28, 
    weekStart: "2026-04-06",
    titleEn: "God's Final Words to Israel", 
    titleZh: "上帝给以色列最后的话", 
    passage: { book: "Malachi", chapterStart: 1, chapterEnd: 4 },
    doctrineEn: "Covenant",
    doctrineZh: "圣约",
    highlightedPassage: { book: "Malachi", chapterStart: 3, verseStart: 18, chapterEnd: 3, verseEnd: 18 },
    highlightedVerseZh: "“那时，你们必归回，将善人和恶人，侍奉上帝的和不侍奉上帝的，分别出来。”"
  },
  { 
    id: 29, 
    weekStart: "2026-04-13",
    titleEn: "Review and Moving Forward", 
    titleZh: "回顾与前行", 
    passage: undefined,
    doctrineEn: "Church",
    doctrineZh: "教会",
    highlightedPassage: { book: "Nehemiah", chapterStart: 9, verseStart: 33, chapterEnd: 9, verseEnd: 33 },
    highlightedVerseZh: "“在一切临到我们的事上，你却是公义的，因你所行的是诚实，我们所做的是邪恶。”"
  },
  { 
    id: 30, 
    weekStart: "2026-04-20",
    titleEn: "Year-End Reflection", 
    titleZh: "今年课程的反思", 
    passage: undefined, 
    isOptional: true,
    doctrineEn: "Reflection",
    doctrineZh: "反思",
    highlightedPassage: undefined,
    highlightedVerseZh: undefined
  },
];

export const VALIDATION_RULES = {
  step1: { min: 0, max: 20 },
  step2: { min: 2, max: 4 },
  step3: { maxCharsZh: 40, maxWordsEn: 20 },
};

export const UI_STRINGS = {
  en: {
    settings: "Settings",
    language: "Language",
    langName: "English",
    lesson: "Lesson",
    steps: ["Observation", "Segmentation", "Topic Sentence", "Main Idea", "Application", "Preview & Submit"],
    next: "Next",
    review: "Go to Review",
    back: "Back",
    submit: "Submit Assignment",
    exportPDF: "Export PDF",
    submitted: "Submitted",
    save: "Save to Cloud",
    login: "Sign in with Google",
    logout: "Logout",
    bible: "Scripture",
    loading: "Loading Bible...",
    validationError: "Please fix errors before proceeding.",
    step1Hint: "List up to 20 objective facts.",
    step1Warning: "You can proceed to the next step.",
    step2Hint: "Divide into 2-4 segments with summaries and refs.",
    step3Hint: "One grammatically complete sentence (Please input up to 20 words).",
    step4Hint: "Timeless truth (No specific prefix required).",
    step5Hint: "One application question per segment.",
    preview: "Preview Assignment",
    confirmSubmit: "Confirm Submission",
    cancel: "Cancel",
    at: "at",
    doctrine: "Doctrine",
    highlightedScripture: "Highlighted Scripture",
    // PDF Labels
    pdfClass: "Class",
    pdfTopic: "Topic",
    pdfPassage: "Passage",
    pdfExported: "Exported",
    pdfUser: "User",
    pdfContent: "CONTENT",
    pdfDivision: "DIVISION",
    pdfSubject: "SUBJECT",
    pdfAim: "AIM",
    pdfApplication: "APPLICATION",
    pdfApplicationLabel: "Application Question",
    submitSuccess: "Assignment submitted successfully!",
  },
  'zh-hans': {
    settings: "设置",
    language: "语言",
    langName: "简体中文",
    lesson: "课程",
    steps: ["内容列项", "分段", "主题句", "主旨", "生活应用", "预览与提交"],
    next: "下一步",
    review: "去预览",
    back: "上一步",
    submit: "提交作业",
    exportPDF: "导出 PDF",
    submitted: "已提交",
    save: "同步到云端",
    login: "使用 Google 登录",
    logout: "登出",
    bible: "查经经文",
    loading: "正在加载经文...",
    validationError: "请在继续之前修正错误。",
    step1Hint: "列出 20 项以内的客观事实。",
    step1Warning: "您可以继续进行下一步。",
    step2Hint: "划分为 2-4 段，并总结内容精要（包含起始与结束经文）。",
    step3Hint: "一个完整的句子（请输入 40 字内）。",
    step4Hint: "表达一个属灵原则（不限开头）。",
    step5Hint: "每个分段对应一个应用问题。",
    preview: "预览作业",
    confirmSubmit: "确认提交",
    cancel: "取消",
    at: "于",
    doctrine: "教义",
    highlightedScripture: "重点经文",
    // PDF Labels
    pdfClass: "课程次序",
    pdfTopic: "题目",
    pdfPassage: "经文范围",
    pdfExported: "导出时间",
    pdfUser: "姓名",
    pdfContent: "内容列项 (CONTENT)",
    pdfDivision: "分段 (DIVISION)",
    pdfSubject: "主题句 (SUBJECT)",
    pdfAim: "主旨 (AIM)",
    pdfApplication: "生活应用 (APPLICATION)",
    pdfApplicationLabel: "应用问题",
    submitSuccess: "作业提交成功！",
  },
  'zh-hant': {
    settings: "設置",
    language: "語言",
    langName: "繁體中文",
    lesson: "課程",
    steps: ["內容列項", "分段", "主題句", "主旨", "生活應用", "預覽與提交"],
    next: "下一步",
    review: "預覽作業",
    back: "上一步",
    submit: "提交作業",
    exportPDF: "匯出 PDF",
    submitted: "已提交",
    save: "同步到雲端",
    login: "使用 Google 登錄",
    logout: "登出",
    bible: "查經經文",
    loading: "正在加載經文...",
    validationError: "請在繼續之前修正錯誤。",
    step1Hint: "列出 20 項以內的客觀事實。",
    step1Warning: "您可以繼續進行下一步。",
    step2Hint: "劃分為 2-4 段，並總結內容精要（包含起始與結束經文）。",
    step3Hint: "一個完整的句子（請輸入 40 字內）。",
    step4Hint: "表達一個屬靈原則（不限開頭）。",
    step5Hint: "每個分段對應一個應用問題。",
    preview: "預覽作業",
    confirmSubmit: "確認提交",
    cancel: "取消",
    at: "於",
    doctrine: "教義",
    highlightedScripture: "重點經文",
    // PDF Labels
    pdfClass: "課程次序",
    pdfTopic: "題目",
    pdfPassage: "經文範圍",
    pdfExported: "匯出時間",
    pdfUser: "姓名",
    pdfContent: "內容列項 (CONTENT)",
    pdfDivision: "分段 (DIVISION)",
    pdfSubject: "主題句 (SUBJECT)",
    pdfAim: "主旨 (AIM)",
    pdfApplication: "生活應用 (APPLICATION)",
    pdfApplicationLabel: "應用問題",
    submitSuccess: "作業提交成功！",
  }
};
